### ISSUE TITLE
Rename this project

### ISSUE THREAD

**Issue by chadhietala** [chadhietala/ember-cli-pre-packager#46]
I'm proposing to change the name of the project to `ember-cli-linker` or `broccoli-linker` as pre-packager is extremely vague.  Linker describes this much better as we take internal and external imports and link them to their final output, which is much more aligned with what traditional linker does.

**Comment by stefanpenner** [comment]
broccoli-linker would be good, assuming it is and continues to be decoupled enough to use without ember-cli

**Comment by chadhietala** [comment]
There are only a 2 areas off the top of my head that make assumptions of ember-cli things.
1. The default whitelist
2. How items in a test folder are handled

These seem like the should be able to be passed in.

**Comment by stefanpenner** [comment]
> The default whitelist
> How items in a test folder are handled
> These seem like the should be able to be passed in

:+1:

**Comment by stefanpenner** [comment]
also, +1 linker

**Comment by chadhietala** [comment]
Forgot that there is an object of `treeDescriptors` that get passed in along with the array of trees. A descriptor looks like the following.

```
addon.pkg.name: {
      packageName: addon.pkg.name,
      root: addon.root,
      pkg: addon.pkg,
      nodeModulesPath: addon.nodeModulesPath
}
...
```

This is used as the SSOT so I don't need to infer package names and node module paths for the things being passed in. It also serves a concrete place to start resolving from.

**Comment by chadhietala** [comment]
Going with ember-cli-linker as it is currently not generic enough. We should get to the point where this is generic though.
