### ISSUE TITLE
deletions don't appear to be always correctly removed

### ISSUE THREAD

**Issue by stefanpenner** [chadhietala/ember-cli-pre-packager#51]
ES
1. `import merge from 'lodash-es/object/merge'`
2. `import merge from 'lodash-es/utilies/noop'`

merge and its deps are not correctly pruned.

potentially related: https://github.com/babel/broccoli-babel-transpiler/pull/39

**Comment by chadhietala** [comment]
Closed in #53l. Although something like babel/broccoli-babel-transpiler#39 needs to land or a fix to cauliflower-filter.
