### ISSUE TITLE
may be always exporting the dep-graph.dot file

### ISSUE THREAD

**Issue by stefanpenner** [chadhietala/ember-cli-pre-packager#72]
likely just something we want in debug mode.

**Comment by chadhietala** [comment]
We want to always export this so downstream as ember cli could open up an endpoint in the dev server that like `/<APP_NAME>-dependency-graph` and have it show something like this http://cpettitt.github.io/project/dagre-d3/latest/demo/interactive-demo.html

**Comment by stefanpenner** [comment]
@chadhietala if this is relatively free, then im down for leaving it on all the time.

**Comment by chadhietala** [comment]
Seems pretty cheap. Closing for now.
